### ISSUE TITLE
[Visual Studio] Update to Azure Functions VSIX fails because the VSIX installer can't uninstall the current version

### ISSUE THREAD

**Issue by justcla** [Azure/Azure-Functions#517]
User "Markus Strobl" asked [question](https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools#qna) on Marketplace:

---
When i try to update from 15.0.30901.0 to 15.0.30923.0 the update process fails because the VSIX installer can't uninstall the current version of the plugin.

The install log shows the following error:

29.09.2017 10:55:51 - Install Error : System.InvalidOperationException: Uninstall of Azure Functions and Web Jobs Tools failed. To uninstall this extension please uninstall all of the following components: Microsoft Azure WebJobs Tools, Microsoft Azure WebJobs Tools, Azure development prerequisites, Azure development
at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges, Version targetedVSVersion)
at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

However, if i uninstall the suggested components, the extension still doesn't uninstall. The error message just changes to:

29.09.2017 10:55:51 - Install Error : System.InvalidOperationException: Uninstall of Azure Functions and Web Jobs Tools failed. To uninstall this extension please uninstall all of the following components: 

(no components listed)

**Comment by justcla** [comment]
Mark, could you please share the Setup and VSIXInstaller logs from your %temp% directory?
Example log files:
- C:\Windows\Temp\VSIXInstaller_e0cd30c3-8474-4a10-a206-0d2f27f6da15.log
- C:\Windows\Temp\dd_setup_20170927125933.log
- C:\Windows\Temp\dd_setup_20170927125933_errors.log

**Comment by marxxxx** [comment]
Hi @justcla !
Of course, i've attached the requested logs of the last  @days.
[Temp_dd_setup.zip](https://github.com/Azure/Azure-Functions/files/1348100/Temp_dd_setup.zip)
[Temp_vsixinstaller.zip](https://github.com/Azure/Azure-Functions/files/1348101/Temp_vsixinstaller.zip)

**Comment by justcla** [comment]
Thanks Mark. We'll check out the logs and see if we can figure out what's going on.

**Comment by obok** [comment]
I've got similar errors with exception that components list to uninstall is not empty:
> Microsoft Azure WebJobs Tools, Microsoft Azure WebJobs Tools, Azure development prerequisites, Azure development
Notice WebJobs Tools being there twice.

I've copied logs from Temp folder:
[VSIXInstaller_logs.zip](https://github.com/Azure/Azure-Functions/files/1355500/VSIXInstaller_logs.zip)

But they don't seem to be relevant. So I've also include logs available from UI:
![image](https://user-images.githubusercontent.com/8970954/31172423-c945a0c4-a903-11e7-983a-1d18955c729d.png)
[VSIXInstaller_39fb053c-4b6f-4939-9ecf-9b3ced79e821.log](https://github.com/Azure/Azure-Functions/files/1355513/VSIXInstaller_39fb053c-4b6f-4939-9ecf-9b3ced79e821.log)

**Comment by ssashok10** [comment]
I am facing the exact issue

**Comment by justcla** [comment]
If it’s an upgrade failing to uninstall, it’s very likely that you ran into a known issue where VS installer and VSIXInstaller have a race condition that results in VS installer overwriting what VSIXInstaller laid down. 

Can you please help us by running http://aka.ms/vscollect so we can take a look?

**Comment by justcla** [comment]
Note: Logs from Marxxx show that the auto-update (performed by the VS installer) failed to update the extension because there was an issue with the certificate.

> 02.10.2017 08:30:16 - VSIXAutoUpdate :  AutoUpdate results on Visual Studio Enterprise 2017
02.10.2017 08:30:16 - VSIXAutoUpdate result in error when updating extension:
02.10.2017 08:30:16 - 		Microsoft.VisualStudio.Web.AzureFunctions-Azure Functions and Web Jobs Tools-15.0.30923.0
02.10.2017 08:30:16 - 		CertError001: Certificate check failed. The certificate information of the upgrade does not match with the certificate information of the  extension that is already installed.

**Comment by elvirdolic** [comment]
I have the same issue

**Comment by jstevenson81** [comment]
I have the same issue as obok.  My log is attached as well
[VSIXInstaller_4e849485-139b-4a98-a101-02cabd6e8c2b.log](https://github.com/Azure/Azure-Functions/files/1361090/VSIXInstaller_4e849485-139b-4a98-a101-02cabd6e8c2b.log)

**Comment by justcla** [comment]
Thanks Jonathan.
Your logs show a different error to the other users.

`Package 'Microsoft.VisualStudio.Web.AzureFunctions,version=15.0.30923.0' failed to install. System.IO.IOException: The file 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs\catalog.json' already exists.`

**Comment by cpunella** [comment]
Hi, I have the same "Uninstall" issue .

10/6/2017 8:54:17 AM - Install Error : System.InvalidOperationException: Uninstall of Azure Functions and Web Jobs Tools failed. To uninstall this extension please uninstall all of the following components: Microsoft Azure WebJobs Tools, Microsoft Azure WebJobs Tools, Azure development prerequisites, Azure development
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by carlfarmer** [comment]
Hi All,

I found that if I (backup first) delete the contents of;
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs

Then the tools vsix will reinstall.

Essentially there are a load of "file already exists" conflicts.

Hope this helps.

**Comment by justcla** [comment]
Thanks Carl.

**Comment by justcla** [comment]
From the extensibility team:

> As stated previously, this looks like an issue we already know about where VSIXInstaller and Willow run into  race condition and overwrite each other.  This issue is being fixed by the setup engine, but without those full logs we can’t tell if that’s indeed the case.  

Can you please help us by running http://aka.ms/vscollect so we can take a look?

**Comment by carlfarmer** [comment]
@justcla Done.

**Comment by justcla** [comment]
Thanks Carl. There should be a vslogs.zip file in your %temp% directory.
`ie. C:\Users\<username>\AppData\Local\Temp\vslogs.zip`

Would you be able to post that somewhere and send us a link?
Thanks

Note: Usually people upload them to a OneDrive location, or if you submit the feedback through VS feedback, then you have the option to do it there too.

**Comment by justcla** [comment]
The issue raised in the first comment of this thread relates to a race condition occurring between the VS installer and the VSIX installer. The issue was [reported on Developer Community](https://developercommunity.visualstudio.com/content/problem/112591/failed-to-install-redgatereadyrollversion114154999.html) in relation to a different extension, but the root cause was the same.
A fix will be released in 15.5 for the Setup Engine to re-check the state of the install and throw an exception if changes have been made since it was called. That should stop this problem from occurring in the future.

For now, the best known fix is to uninstall and reinstall the affected instance of Visual Studio.
Alternatively, you could try the fix suggested by Carl Farmer above:

> I found that if I (backup first) delete the contents of;
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs
Then the tools vsix will reinstall.

**Comment by obok** [comment]
@justcla I've sent you a link to my vslogs.zip to your work mailbox. 
@carlfarmer Unfortunately your workaround didn't work in my case :(

**Comment by carlfarmer** [comment]
@justcla  Uploaded to; https://1drv.ms/u/s!AuTGh4B9ChjFgZNPkGi9C5fMdxO8Aw

**Comment by justcla** [comment]
Thanks for the logs, guys. We will analyze them to determine if it's the race condition - or some other problem.

**Comment by tinaschrepfer** [comment]
We took a look at the logs for the uninstall issue:

10/6/2017 8:54:17 AM - Install Error : System.InvalidOperationException: Uninstall of Azure Functions and Web Jobs Tools failed. To uninstall this extension please uninstall all of the following components: Microsoft Azure WebJobs Tools, Microsoft Azure WebJobs Tools, Azure development prerequisites, Azure development

Would you mind sending us this file on disk? C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs\catalog.json.

Also, when you go to extensions and updates, what version of Azure does it say is installed?

Thanks,

Tina

**Comment by obok** [comment]
@tinaschrepfer Here's mine:
[catalog.zip](https://github.com/Azure/Azure-Functions/files/1372909/catalog.zip)

**Comment by tinaschrepfer** [comment]
@obok, it seems like the latest version of Azure Functions is actually installed on your instance of VS, but for some reason the extensions cache got corrupted.  When you go to Extensions and Updates dialog, what version does it show you have?

**Comment by tinaschrepfer** [comment]
@obok, Carl's workaround won't work for since you're hitting a totally different issue.  Can you zip up the contents of these places and send them to us: 
* C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs
* %localappdata%\Microsoft\VisualStudio\15.0_[InstanceId]\Extensions 

Thanks,

Tina

**Comment by neoDD69** [comment]
Hi, 
I had the same problem and seems I've found a solution.

following the suggestion of @carlfarmer  (delete the folder of WebJobs extension) I've deleted it, but the problem was still there.

Reading the LOG I've found an interesting line ... the last ;) :
11/10/2017 16:41:45 - An extension with a matching Identifier is already installed to this product. The extension is installed to C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\JR25FYXT.SZI\

What !! 

I've moved the \JR25FYXT.SZI\ folder to another disk, started VS, clicked on the "update notice" and let the installer do his job .... **and IT WORKED**!

I hope this help someone else.

PS: I've noted that my folder \EXTENSIONS\ is filled with a lot (dozens) of folder with an non-human-name ... anyone have any idea why?

**Comment by tinaschrepfer** [comment]
@neoDD69, can you zip up the contents of JR25FYXT.SZI and upload it somewhere for us to view?  If you could run http://aka.ms/vscollect and upload the zip file produced that would help us root cause the issue too.

The random names you see under Extensions are all per-machine extensions installed for your VS instance.  By default, extensions do not specify a static install path and gets a generated random root name.

Thanks,

Tina

**Comment by neoDD69** [comment]
@tinaschrepfer 
Done, you can found 2 zips here https://1drv.ms/f/s!AqVVpXmgRUv1mM90BnzdIN2BWbdFsg 
Ciao

Davide

**Comment by neoDD69** [comment]
@tinaschrepfer thank you for the answer about the non-human-folderNames.

There is a way to known which of them can be deleted?

**Comment by justcla** [comment]
Each folder represents one extension. If you navigate to the folder you will see the files. Simply looking at the file names might give you an idea which extension it is. To be exact, open the extension.manifest file in each directory and look for the title of the extension.

You can delete the entire directory for any extension you don't want on your installation.
When I do this, I typically delete all the cache files in the extensions directory so that VS will rebuild the extension cache on next load.

**Comment by tinaschrepfer** [comment]
@neoDD69, I took a look at your logs but I'm baffled by why the Azure Functions extension is installed into a random directory instead of the static directory  "Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs".  The VSIX on the marketplace clearly indicates that it should be installed to the static directory, and not a random directory.  So I'm confused how this could ever happen.  From the logs, I also don't see anything from setup that indicates files were laid down to JR25FYXT.SZI directory.  In fact, some of the logs seem to be corrupted in that they're not complete.  For now, what you did as work around should work.

We can't reproduce this issue internally, so the only guess I could think of why this happened is somehow there were extension authoring issues where an incorrectly authored VSIX was uploaded to the Marketplace and then later corrected.

On a separate note, please don't start deleting folders from Common7\IDE\Extensions, or any folders installed by VS for that matter.  In this case, it worked for you because there was a duplication issue we're not sure what was the root cause.  In general, deleting directories laid down by VS on your own will likely corrupt your instance of VS.

**Comment by neoDD69** [comment]
@tinaschrepfer, 
thank you for investigating.
I understood and agree with you.

Note that I use VS 15.x from early RCs (from last year).
May be that one update with no definitive configs have done this situation?

Ok, I will not delete Exestions folders... but I've a LOT of folders: 52 (from feb '17 to yesterday) !

**Comment by obok** [comment]
@tinaschrepfer 
After a try with carlfarmer workaround my WebJobs folder is empty :) 
Here's how it looked before: https://drive.google.com/open?id=0B2bV1qKi08ytNXNqOFZmbWZHNWM

In the meantime new version of tools has been released. I tried installing it with the same result (failure). WebJobs folder still empty. 
Here's what Extensions folder looks like now: [Extensions.zip](https://github.com/Azure/Azure-Functions/files/1383786/Extensions.zip)
And VSIX installer log: [VSIXInstaller_073794c0-7c01-4eec-b579-c691cc6552e0.log](https://github.com/Azure/Azure-Functions/files/1383787/VSIXInstaller_073794c0-7c01-4eec-b579-c691cc6552e0.log)

**Comment by tinaschrepfer** [comment]
@obok, it looks like you zipped up the Extension folder in %localappdata%.  Can you zip up the contents in Common7\IDE\Extensions (under program files)?

Thanks!

**Comment by obok** [comment]
@tinaschrepfer, here's also Extensions folder from under Program Files: https://drive.google.com/open?id=0B2bV1qKi08ytWThQTzFCT0Y5Ykk.

**Comment by tinaschrepfer** [comment]
@obok, I took a look at your Extensions folder and it looks like you too ran into an issue where the extension got installed into a random directory at some point.  Still not sure how that could have happened  short of an incorrectly authored extension being mistakenly uploaded to the gallery.  At this point, your best bet is to run repair on your instance of VS to get you back to a clean state. 

If in the future you see that Azure Web Jobs extension is installed to a random directory (something other than "Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs"), please let us know and share the extension you installed with us.

Thanks!

Tina

**Comment by obok** [comment]
@tinaschrepfer 
Unfortunately the repair **did not** work.
![image](https://user-images.githubusercontent.com/8970954/31849779-6a1bbca8-b648-11e7-814b-98b272049863.png)

But uninstalling Microsoft Azure WebJobs Tools from Individual components of the installer and installing them again **worked**.
![image](https://user-images.githubusercontent.com/8970954/31849790-9cb0eb66-b648-11e7-8f75-609c9d7f7a41.png)

After that running an update from Extensions and Updates was sucessful.

![image](https://user-images.githubusercontent.com/8970954/31849816-1e9d23d8-b649-11e7-8662-518561d1a891.png)

![image](https://user-images.githubusercontent.com/8970954/31849775-45c74a16-b648-11e7-95c6-8986336c98d7.png)

**Comment by obok** [comment]
@tinaschrepfer 
Unfortunately notification that Azure WebJobs Tools needs to be updated keeps popping up.
When trying to run an update it shows:

![image](https://user-images.githubusercontent.com/8970954/31849897-5ce4cf96-b64a-11e7-9d6a-4712c9f129d3.png)

I will try complete uninstall of Visual Studio.

**Comment by obok** [comment]
@tinaschrepfer 
Complete reinstall of Visual Studio helped.
Azure Functions and Web Jobs Tools could be successfully updated **AND** notification stopped popping up.

**Comment by codekoenig** [comment]
15.5 still does not fix this issue. That's frustrating, seems a reinstall is inevitable.

**Comment by neoDD69** [comment]
@codekoenig I had too ... I solved with this steps:
- after VS start the update of VSIX and the installer remain still without doing nothing
- reboot the PC
- go in %temp% dir
- find the more RECENT .vsix and run-it
- all should be run ok

It seems that VS 17 from 15.4 after you start the first instance of it and then close, let some things -running that block any type of setup (I've problem also with a setup of MindManager!)

PS: sorry for the "fast english" .... ;)

**Comment by codekoenig** [comment]
@neoDD69 Thanks - unfortunately, in my case also this did not help.

**Comment by shurub3l** [comment]
I have the same error when trying to install the Azure Functions and Web Jobs Tools extension. Here is the error from the log:

> Install Error : System.InvalidOperationException: Installation of Azure Functions and Web Jobs Tools failed. To install this extension please install at least one of the following components: Microsoft Azure WebJobs Tools
>    at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.LoadComponent(IDependencyGraph dGraph, Boolean& isProductComponent)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by michel-weber** [comment]
Still not fixed - even with Visual Studio 15.5.6:

Install Error : System.InvalidOperationException: Uninstall of Azure Functions and Web Jobs Tools failed. To uninstall this extension please uninstall all of the following components: Microsoft Azure WebJobs Tools, Microsoft Azure WebJobs Tools, Azure development prerequisites, Azure development
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

And the log itself:
[VSIXInstaller_2badfb35-7a84-4a1c-b245-aa08eaa09841.log](https://github.com/Azure/Azure-Functions/files/1694105/VSIXInstaller_2badfb35-7a84-4a1c-b245-aa08eaa09841.log)

**Comment by ederome** [comment]
Exact same error as michel-weber, I'm on Windows 10, VS Studio 2017 15.5.6 too, with admin rights

**Comment by ederome** [comment]
15.5.7 also has the same error for trying to install the update. ..

**Comment by jdavid82** [comment]
Had the same error, didn't need to re-install VS, just downloaded and ran the VS installer and then checked the checkbox for Azure Development and then opened VS and installed updates. It worked fine after that.

**Comment by Monte-Christo** [comment]
jdavid82's fix does not work for me. Same error:

20-Jun-18 19:02:20 - Install Error : System.InvalidOperationException: Diese Version der Erweiterung liegt außerhalb des unterstützten Bereichs und kann nicht installiert werden.

In English: "This version of the extension is outside the supported range and cannot be installed."

**Comment by simeyla** [comment]
Looks like Azure Functions (which I only installed yesterday for the first time) broke my entire VS extensions. 
Can't even install the portability analyser vsix :-(

**Comment by artemious7** [comment]
@obok 's [solution](https://github.com/Azure/Azure-Functions/issues/517#issuecomment-338374883) worked for me too:
> **uninstalling** Microsoft Azure WebJobs Tools **from Individual components of the installer** and installing them again worked.
> **After that running an update** from Extensions and Updates was sucessful.

**Comment by ColbyTresness** [comment]
In VS2019 this is fixed as the extension will be a part of the product.
