### ISSUE TITLE
[Visual Studio] Toolings for Azure Functions not get along with .NET Core projects

### ISSUE THREAD

**Issue by justinyoo** [Azure/Azure-Functions#86]
Hi, Team.

I really appreciate for your hard working efforts about the preview release of Visual Studio Toolings for Azure Functioins today.

However, I found a critical issue when I dealt with .NET Core projects in Visual Studio 2015 U3. Before installing this, it was totally OK. I've been working on .NET Core projects everyday. Suddenly after installing this preview, every single .NET Core project crashes.

I'v got all prerequisites for the tooling, by the way.

**Reproducing Issues**

* **Targeting .NET Framework 4.6**
  1. Open Visual Studio 2015U3.
  2. Create Azure Functions (Preview) project.
  3. Works as expected.

* **Targeting .NET Core**
  1. Open Visual Studio 2015U3.
  2. Create ASP.NET Core (.NET Core) Application project.
  3. Crash!

![image](https://cloud.githubusercontent.com/assets/1538528/20809117/1ea5a754-b859-11e6-8ead-e7d7791c0e93.png)

* **Opening existing .NET Core app.**
  1. Double click an existing ASP.NET Core solution.
  2. Crash!

![image](https://cloud.githubusercontent.com/assets/1538528/20809172/470f8d2c-b859-11e6-872b-fc9b21c96df9.png)

Now, I can't open any of .NET Core project unless I uninstall the tooling. Would you mind having a look in your earliest convenient?

/cc: @lindydonna

**Comment by lindydonna** [comment]
My college on the Visual Studio team said the following: "This is usually MEF cache corruption. Running devenv /setup at the developer command prompt (running as administrator) should fix it."

@justinyoo can you give that a try? I'll try to repro myself shortly.

**Comment by ctolkien** [comment]
@madskristensen wrote a VS extension to clear the MEF cache, as it seems to choke all the time:
https://github.com/madskristensen/ClearComponentCache/

And marketplace link:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache

Much less intrusive than `devenv /setup`

**Comment by justinyoo** [comment]
@lindydonna I've run devenv /setup at the developer command prompt console as admin and got this error

![image](https://cloud.githubusercontent.com/assets/1538528/20817616/8da9afd6-b874-11e6-9611-55cf6864b6e6.png)

I also intalled the VS extension that @ctolkien suggested, but still no luck. If MEF cache is corrupted, any solution files can't be loaded, I suspect, but only .NET Core related solutions are not being opened.

**Comment by lindydonna** [comment]
@justinyoo Could you try deleting "AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache and MEFCacheBackup" then restarting VS?

Sorry you're running into so many issues! :-/

**Comment by justinyoo** [comment]
@lindydonna Oops! I ran the developer command prompt console as a **real** admin mode lol. Now the error message came upon the screen disappeared! &ndash; OK!

I've now deleted both `ComponentModelCache` and `MEFCacheBackup` folders from the `AppData\Local\Microsoft\VisualStudio\14.0\` directory.

Still have the same issue.

![image](https://cloud.githubusercontent.com/assets/1538528/20818722/2d98175c-b87b-11e6-9cbc-4089ca7a7653.png)

**Comment by lindydonna** [comment]
We can repro as well, investigating. Thanks for your patience!

**Comment by gibwar** [comment]
I would like to point out that uninstalling still leaves .Net Core projects in a broken state (at least web ones). After removing the Functions preview I still get the above errors and now get the following error on attempting to run the project:

```
---------------------------
Microsoft Visual Studio
---------------------------
The project doesn't know how to run the profile IIS Express.
---------------------------
OK   
---------------------------
```

**Comment by lindydonna** [comment]
Update: we've found the source of the problem (a conflict with the GUID used for the project type). On the announcement blog post, customers said that they were able to unload and reload .NET core projects and that solved the problem: https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/

**Comment by gibwar** [comment]
I've installed the latest release and most of the problems are fixed. However, in a solution with 1 .Net Core Web Application and 5 .Net Core libraries, the Add -> New Item dialog is still broken (shows no templates, can only be cancelled), meaning we still have to use the Add New File extension mentioned in the blog post.

**Comment by lindydonna** [comment]
@gibwar This is probably because the initial version of the Functions tooling was using the same internal GUID for the project type as netcore projects, so Add New File on a netcore project still thinks it's a Functions project.

To fix, do one of the following:

1. In an **administrator** command prompt, run `devenv /setup`

2. Use the "ClearComponentCache" extension (NOTE: I have not tried this myself, but this was suggested by other customers).

  - https://github.com/madskristensen/ClearComponentCache/
  - Marketplace link:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache

**Comment by lindydonna** [comment]
I'm closing this issue as we have fixed the .NET core project issues. If you still see weird problems with .NET core projects even with the latest version of the package, try the workaround steps above to clear the MEF cache.
