### ISSUE TITLE
Error: Can't figure out which ctor to call

### ISSUE THREAD

**Issue by grik001** [Azure/Azure-Functions#910]
Hi, is it possible to use the following library(Microsoft.Azure.WebJobs.EventHubs) with .Net Framework 4.7? 

![image](https://user-images.githubusercontent.com/27157850/44036286-b2e73d42-9f11-11e8-96d7-99e4b449e415.png)

I keep getting the following error:

![image](https://user-images.githubusercontent.com/27157850/44036305-bded7080-9f11-11e8-95e6-87b4a25391db.png)

This is the function.json set for the azure function:

![image](https://user-images.githubusercontent.com/27157850/44036535-4b469880-9f12-11e8-8a2a-71dc8a180b60.png)

The following packages are installed as Nugets:

![image](https://user-images.githubusercontent.com/27157850/44036770-ea4435d2-9f12-11e8-825d-746d08ac9f91.png)

**Comment by paulbatum** [comment]
Uh, ignore my previous answer. I'm going to assume you're on V2. I think the problem is that you're using Microsoft.Azure.EventHubs 2.1.0. Please try downgrading to 1.0.3. (your processor reference should also be downgraded)

We have a issue tracking the need to upgrade the extension to work with the latest event hubs client SDK, should be resolved in a few weeks:
https://github.com/Azure/azure-webjobs-sdk/issues/1710

For a little more context, also see my comment here:
https://github.com/Azure/azure-webjobs-sdk/issues/1484#issuecomment-390369045

**Comment by grik001** [comment]
Hi,

Thanks for your reply. Will downgrade wand update you first thing tomorrow.

**Comment by grik001** [comment]
Hi @paulbatum,

I have downgraded both packages but I am still getting the same CTOR error. I have delete
d my function and republished to be 100% sure.

![image](https://user-images.githubusercontent.com/27157850/44073377-e62c4c6a-9f93-11e8-9f07-96d1b50d788d.png)

**Comment by grik001** [comment]
Hi @paulbatum ,

You were right about the v1/v2. When publishing a popup was asking me to match my local version and I was clicking yes, thus reverting my function from **beta** to **v1**.

Although now I am not getting the error, I still am not receiving events from EventHub. When I execute the function on the portal manually no logs are being written to the console which for me indicated the **Run** is not being executed.

**Comment by grik001** [comment]
I have managed to get the above function to work. I was following the following guide:

![image](https://user-images.githubusercontent.com/27157850/44190238-15b7db00-a126-11e8-9484-95afd6ed92bf.png)

The guide specifies 3.0.0-beta5 but after downgrading to 2.2.0 it started working.

![image](https://user-images.githubusercontent.com/27157850/44190264-354f0380-a126-11e8-9aa8-2701957f94f9.png)

![image](https://user-images.githubusercontent.com/27157850/44190203-f751df80-a125-11e8-8503-0ae68f39e7d7.png)

I am now facing a new issue I will create a new ticket since it is not related, feel free to close this thread:

**Comment by paulbatum** [comment]
The 2.2.0 package is for V1, while the 3.0.0-beta5 package is for V2. See the information on this page:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs

Closing this as suggested.
