### ISSUE TITLE
Cannot compile with sdk 1.021

### ISSUE THREAD

**Issue by maddentist** [Azure/Azure-Functions#950]
Compilation fails with the folliwing after update sdk to 1.0.21

7>aero.airprox.backend.functions.korolev.base_stations -> C:\Code\AIRPROX_Backend\aero.airprox.backend.functions.korolev.base_stations\bin\Debug\netstandard2.0\bin\aero.airprox.backend.functions.korolev.base_stations.dll
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'Microsoft.Azure.WebJobs, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le fichier spécifié est introuvable.
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Nom de fichier : 'Microsoft.Azure.WebJobs, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeMethodInfo target)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à MakeFunctionJson.MethodInfoExtensions.HasFunctionNameAttribute(MethodInfo method)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à MakeFunctionJson.FunctionJsonConverter.<GenerateFunctions>d__9.MoveNext()
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    à MakeFunctionJson.FunctionJsonConverter.TryRun()
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : 
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : AVT : la journalisation de liaison d'assembly est désactivée.
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Pour activer la journalisation des échecs de liaison d'assembly, attribuez la valeur 1 à la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD).
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Remarque : une certaine perte de performance est associée à l'enregistrement dans le journal des échecs de liaison d'assembly.
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Pour désactiver cette fonctionnalité, supprimez la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog].
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : 
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Error generating functions metadata
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :
7>C:\Users\Mathi\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Metadata generation failed.
7>Done building project "aero.airprox.backend.functions.korolev.base_stations.csproj" -- FAILED.

these are the package referenced in the project :
 <ItemGroup>
    <PackageReference Include="aero.airprox.global.net" Version="1.2.7" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.8.0-beta1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.1-rc1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="3.0.0-beta8" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.21" />
  </ItemGroup>

Help or workaround needed

(BTW it worked pretty well with the previous sdk version 1.0.19. However, there were some strange/random errors with extensions package that is why I would prefer to be as close as possible to release versions)

**Comment by phantomazo** [comment]
Any updates on workaround?
I am experiencing the same.

**Comment by christoferlof** [comment]
I'm also experiencing this. 1.0.19 works well. 1.0.21 breaks the build with *System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.WebJobs, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.*

**Comment by kirmak** [comment]
1.0.21 Cannot build with error: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.WebJobs, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by piyushkhanna** [comment]
1.0.21 Cannot build with error: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.WebJobs, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by Badabum** [comment]
The same thing...

**Comment by roryprimrose** [comment]
This happens if you reference another library that pulls in ```Microsoft.Azure.WebJobs 3.0.0-beta8```. The other library needs to be updated to ```Microsoft.Azure.WebJobs 3.0.0-rc1``` to avoid this issue.

**Comment by kirmak** [comment]
I my case, I referenced AzureAdvocates.WebJobs.Extensions.SignalRService library, which was updated to 3.0.0-rc1 with new name and added to azure extensions! - Microsoft.Azure.WebJobs.Extensions.SignalRService.

**Comment by Badabum** [comment]
Facing the same thing with 1.0.22. Checked that none of the packages are dependent on Microsoft.Azure.WebJobs lover than 3.0.0

**Comment by Rambalac** [comment]
Unfortunately ServiceBus package is still beta8.

**Comment by chandlerpelhams** [comment]
> Unfortunately ServiceBus package is still beta8.

It looks like the service bus nuget package was renamed to Microsoft.Azure.WebJobs.Extensions.ServiceBus, which has a stable 3.0.0 release. Referencing the new package resolved the build errors for me.

**Comment by paulbatum** [comment]
@roryprimrose is correct. See [this table](https://github.com/Azure/azure-functions-host/wiki/Updating-your-function-app-extensions#what-nuget-packages-do-i-need) for a list of packages that work together

@chandlerpelhams is correct. Sorry about the confusion this caused, but the service bus package was the one package that was not following our naming convention and often did not appear for users that did searches in NuGet for "webjobs.extensions". If you're on functions 1.x or webjobs 2.x you should reference `Microsoft.Azure.WebJobs.ServiceBus` and if you're on functions 2.x or webjobs 3.x you should reference `Microsoft.Azure.WebJobs.Extensions.ServiceBus`.

I'm going to close this issue as I think the reported issues are resolved using the information above. If you've followed this guidance and are still running into issues, leave a comment and include a list of your references packages from your csproj.

**Comment by adammodlin** [comment]
Hello @paulbatum, I'm still having an issue here. 

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.Azure.ServiceBus, Version=3.0.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c'. The system cannot find the file specified.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.TryLoadRuntimeAssembly(AssemblyName assemblyName, Assembly& assembly) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs:line 235
```

Here's my .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="3.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by paulbatum** [comment]
@adammodlin your csproj looks fine. I will note that it should be basically the same as the csproj that VS generates for you if you make a new function app project, with the exception that VS now makes a .NET core class library instead of a .NET standard class library (but either should work).

I think there must be something else going on here. If you create a brand new function app in VS and select the service bus trigger, do you still get this error? Do you have a reliable set of repro steps?
